left_down_position:
- [0.5, 0.0, 1.4]
- [0.0, 0.0, 3.14]

left_up_position:
- [0.5, 0.0, 1.6]
- [0.0, 0.0, 3.14]

right_down_position:
- [0.3, -0.5, 1.4]
- [0.0, 0.0, 3.14]

right_up_position:
- [0.3, -0.5, 1.6]
- [0.0, 0.0, 3.14]
