left_down_position:
- [0.5, -0.3, 1.4]
- [3.14, 0.0, 1.57]

left_up_position:
- [0.5, -0.3, 1.6]
- [3.14, 0.0, 1.57]

right_down_position:
- [0.38, -0.45, 1.4]
- [3.14, 0.0, 1.57]

right_up_position:
- [0.38, -0.45, 1.6]
- [3.14, 0.0, 1.57]
