#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: arm pos
  component_name: arm
  buttons: [[stop,trigger,stop],
    [home,move,home],
    [folded,move,folded],
    [pregrasp,move,pregrasp],
    [hold,move,hold],
    [sdhmount, move, sdhmount],
    [overtray,move,overtray],
    [wave in,move,wavein],
    [wave out,move,waveout]]
group2:
  group_name: arm traj
  component_name: arm
  buttons: [[stop,trigger,stop],
    [folded-to-look at table,move,folded-to-look_at_table],
    [look_at_table-to-folded,move,look_at_table-to-folded],
    [grasp-to-tray,move,grasp-to-tray],
    [tray-to-folded,move,tray-to-folded],
    [wave,move,wave]]
